### ISSUE TITLE
Accept color option

### ISSUE THREAD

**Issue by contra** [jonjaques/react-loaders#11] opened 2016-06-26 16:59 UTC
Not easy to override via variables when using wepack, seems simpler to pass in the color to the Loader component and it will set it on the divs (overriding the default).

**Comment by jonjaques** [comment] 2016-06-30 22:00
I would like to do this, but unfortunately the animations themselves use a wide variety of properties to actually set the color. For instance, the pacman animation uses a combination of background-color on certain elements, and border-color on others - so I can't uniformly apply the color without encoding all of the animation specific stuff into the library. 

As such, this is currently out of the scope of this component. I would suggest opening this issue or searching existing ones in `loaders.css` to see if there's an easier way of overriding - as I agree it could be easier.

**Comment by contra** [comment] 2016-07-01 04:17
@jonjaques There's only two or three properties - set them all? It doesn't seem like a big deal to set those properties on the divs. You don't need to add any specific logic based on the animation or anything.

**Comment by jonjaques** [comment] 2016-07-14 00:02
Check [this out](https://github.com/jonjaques/react-loaders/blob/gh-pages/components/loader.js#L50)...

All this component does is generate an arbitrary amount of divs and then apply a specific class to the container element. Based on the animation, loaders.css applies styles (bg, border, etc) via `nth-child` targeting specific divs within the container div. 

So the problem is I can't just uniformly apply them against all the divs, I would need to have React "know" about each animation, and I don't really care to encode that info at this time. (PR welcome :smile:)

**Comment by jonjaques** [comment] 2017-04-28 15:55
Closing this because I have no plans to implement this in the lib's current form.

**Closed by jonjaques** 2017-04-28 15:55 UTC
Labels: enhancement
